# Generated by Django 5.2.7 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Upload Aadhaar or other valid ID proof', null=True, upload_to='id_proofs/'),
        ),
    ]
