# Generated by Django 6.0 on 2025-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_homespace_homespacephoto_homespacereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, help_text='Area/Locality within the city', max_length=100),
        ),
    ]
